version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres-nextcloud
    environment:
      POSTGRES_DB: nextcloud
      POSTGRES_USER: nextcloud
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nextcloud-network
    restart: unless-stopped

  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud-app
    ports:
      - "8086:80"
    environment:
      POSTGRES_DB: nextcloud
      POSTGRES_USER: nextcloud
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: postgres
    volumes:
      - nextcloud_data:/var/www/html
    networks:
      - nextcloud-network
    depends_on:
      - postgres
    restart: unless-stopped

  adminer:
    image: adminer:latest
    container_name: adminer-nextcloud
    ports:
      - "8081:8080"
    networks:
      - nextcloud-network
    restart: unless-stopped
    environment:
      ADMINER_DEFAULT_SERVER: postgres

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: unless-stopped
    networks:
      - nextcloud-network

volumes:
  nextcloud_data:
  postgres_data:
  portainer_data:

networks:
  nextcloud-network:
    driver: bridge